info:
  description: "News REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "News"
  version: v1.0
openapi: 3.0.1

paths:
  /news:
    get:
      summary: "Get a paginated list of news articles"
      operationId: "getNewsPage"
      tags:
        - "News"
      parameters:
        - name: "Date"
          in: query
          description: "Search by Date"
          schema:
            type: string
            format: date-time
          required: false
        - name: "page"
          in: query
          description: "Page number (default 1)"
          schema:
            type: integer
            format: int32
        - name: "pageSize"
          in: query
          description: "Items per page (default 20)"
          schema:
            type: integer
            format: int32
        - name: "search"
          in: query
          description: "Search by keyword"
          schema:
            type: string
      responses:
        '200':
          description: "A paginated response of news articles"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsPage"
            application/xml:
              schema:
                $ref: "#/components/schemas/NewsPage"
  /news/{id}:
    get:
      summary: "Get news by id"
      operationId: "getNewsById"
      tags:
        - "News"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "A response of news"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsArticle"
            application/xml:
              schema:
                $ref: "#/components/schemas/NewsArticle"
components:
  schemas:
    # Wrapper for Pagination
    NewsPage:
      type: object
      properties:
        newsArticles:
          type: array
          items:
            $ref: "#/components/schemas/NewsArticle"
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int64
        lastPage:
          type: integer
          format: int32

    # Clean Journal Article Schema
    NewsArticle:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        coverImage:
          type: string
          description: "URL to the cover image"
        date:
          type: string
          format: date-time
        authorName:
          type: string
        image:
          type: string
